// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-kVyGud7PdfjEuiSBLy0J4fJEMgABwyo',
    appId: '1:1075767885823:web:cf6a36e421cfc5031e71ca',
    messagingSenderId: '1075767885823',
    projectId: 'fourdimensions-cba95',
    authDomain: 'fourdimensions-cba95.firebaseapp.com',
    storageBucket: 'fourdimensions-cba95.firebasestorage.app',
    measurementId: 'G-TL199D5VVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2JqvL6TZ6Pyb7Ubtu7iM5bInQVNKSA_o',
    appId: '1:1075767885823:android:c941feb3f8b0cb4b1e71ca',
    messagingSenderId: '1075767885823',
    projectId: 'fourdimensions-cba95',
    storageBucket: 'fourdimensions-cba95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDcT0rHNrbIxIPjcF49lgOQyYoMWyY_PI',
    appId: '1:1075767885823:ios:2eca864f25a406341e71ca',
    messagingSenderId: '1075767885823',
    projectId: 'fourdimensions-cba95',
    storageBucket: 'fourdimensions-cba95.firebasestorage.app',
    iosBundleId: 'com.example.fourdimensions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDcT0rHNrbIxIPjcF49lgOQyYoMWyY_PI',
    appId: '1:1075767885823:ios:2eca864f25a406341e71ca',
    messagingSenderId: '1075767885823',
    projectId: 'fourdimensions-cba95',
    storageBucket: 'fourdimensions-cba95.firebasestorage.app',
    iosBundleId: 'com.example.fourdimensions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-kVyGud7PdfjEuiSBLy0J4fJEMgABwyo',
    appId: '1:1075767885823:web:8d41764832a6d8881e71ca',
    messagingSenderId: '1075767885823',
    projectId: 'fourdimensions-cba95',
    authDomain: 'fourdimensions-cba95.firebaseapp.com',
    storageBucket: 'fourdimensions-cba95.firebasestorage.app',
    measurementId: 'G-DE5K6E0FYW',
  );
}
